/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dailymoney;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAdjuster;
import java.time.temporal.TemporalAdjusters;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon Weatherley
 */
public class dailyMoneyUI extends javax.swing.JFrame
{

    private boolean emptyBalance = false;
    private String formattedBudget;

    /**
     * Creates new form dailyMoneyUI
     */
    public dailyMoneyUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCurrentBankBalance = new javax.swing.JTextField();
        textFieldTodaysDate = new javax.swing.JTextField();
        textFieldNextPayDay = new javax.swing.JTextField();
        textFieldNumberOfDaysLeft = new javax.swing.JTextField();
        textFieldBudgetPerDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Please enter current bank balance (£):");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Todays Date :");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Next pay day :");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Number of days remaining :");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Budget per day :");

        textFieldCurrentBankBalance.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        textFieldCurrentBankBalance.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldCurrentBankBalanceActionPerformed(evt);
            }
        });

        textFieldTodaysDate.setEditable(false);
        textFieldTodaysDate.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        textFieldTodaysDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textFieldTodaysDateActionPerformed(evt);
            }
        });

        textFieldNextPayDay.setEditable(false);
        textFieldNextPayDay.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N

        textFieldNumberOfDaysLeft.setEditable(false);
        textFieldNumberOfDaysLeft.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N

        textFieldBudgetPerDay.setEditable(false);
        textFieldBudgetPerDay.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Available Funds per day");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));

        buttonCalculate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCalculate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonCalculateActionPerformed(evt);
            }
        });

        buttonExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonExit.setText("EXIT");
        buttonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTodaysDate, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(textFieldCurrentBankBalance)
                            .addComponent(textFieldNextPayDay)
                            .addComponent(textFieldNumberOfDaysLeft)
                            .addComponent(textFieldBudgetPerDay)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldCurrentBankBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldTodaysDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNextPayDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldNumberOfDaysLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldBudgetPerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTodaysDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldTodaysDateActionPerformed
    {//GEN-HEADEREND:event_textFieldTodaysDateActionPerformed

    }//GEN-LAST:event_textFieldTodaysDateActionPerformed

    private void textFieldCurrentBankBalanceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textFieldCurrentBankBalanceActionPerformed
    {//GEN-HEADEREND:event_textFieldCurrentBankBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCurrentBankBalanceActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonCalculateActionPerformed
    {//GEN-HEADEREND:event_buttonCalculateActionPerformed
        if (textFieldCurrentBankBalance.getText().equals(""))
        {
            emptyBalance = true;
            JOptionPane.showMessageDialog(null, "Please enter a value for the bank balance");
        }
        else
        {
            emptyBalance = false;
            double currentBalance = Double.parseDouble(textFieldCurrentBankBalance.getText());
            LocalDate today = getTodaysDate();
            LocalDate nextPayDay = getNextPayday(today, 24);
            int numberOfDaysRemaining = (int) ChronoUnit.DAYS.between(today, nextPayDay);
            double budget = 0;
            if (!(numberOfDaysRemaining == 0))
            {
                budget = currentBalance / numberOfDaysRemaining;
                DecimalFormat df = new DecimalFormat("£" + "#,##0.00");
                formattedBudget = df.format(budget);
            }
            else
            {
                formattedBudget = String.valueOf(currentBalance);
            }
            textFieldNumberOfDaysLeft.setText(String.valueOf(numberOfDaysRemaining));
            textFieldNextPayDay.setText(nextPayDay.format(DateTimeFormatter.ofPattern("dd-MMM-yyyy")));
            textFieldBudgetPerDay.setText(formattedBudget);

        }

    }//GEN-LAST:event_buttonCalculateActionPerformed

    private LocalDate getTodaysDate()
    {
        LocalDate today = LocalDate.parse(LocalDate.now().toString());
        textFieldTodaysDate.setText(today.format(DateTimeFormatter.ofPattern("dd-MMM-yyyy")));
        return today;
    }

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonExitActionPerformed
    {//GEN-HEADEREND:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(dailyMoneyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(dailyMoneyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(dailyMoneyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(dailyMoneyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new dailyMoneyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textFieldBudgetPerDay;
    private javax.swing.JTextField textFieldCurrentBankBalance;
    private javax.swing.JTextField textFieldNextPayDay;
    private javax.swing.JTextField textFieldNumberOfDaysLeft;
    private javax.swing.JTextField textFieldTodaysDate;
    // End of variables declaration//GEN-END:variables

    private LocalDate getNextPayday(LocalDate today, int payday)
    {
        return YearMonth.from(today).plusMonths(1).atDay(payday);
    }
}
